Traceback (most recent call last):
  File ".\start.py", line 23, in <module>
    raise ValueError   
ValueError
